### ISSUE TITLE
`async-disk-cache` 1.2.1 breaks Node 0.12 compatibility

### ISSUE THREAD

**Issue by leizhao4** [stefanpenner/broccoli-persistent-filter#101]
Some addons (like [ember-cli-deploy-build](https://github.com/ember-cli-deploy/ember-cli-deploy-build/pull/35) and [torii](https://github.com/Vestorly/torii/pull/322)) are depending on `broccoli-persistent-filter` and are still supporting Node 0.12 for some reason.

Is it a good idea to release a version of `broccoli-persistent-filter` which point to `async-disk-cache` <=1.2.0? Or should those addon developers drop 0.12 support instead?

**Comment by stefanpenner** [comment]
Just a heads-up node 0.12 is no longer maintained by the node folks, although it is not the intention to have broken anyone. It is a tad tricky to support non-supported versions.

Node's Long-term support policy is outlined here: https://github.com/nodejs/LTS

**Comment by stefanpenner** [comment]
I also worked-around the 0.12 node support issue https://github.com/stefanpenner/async-disk-cache/pull/45
