### ISSUE TITLE
Consider dropping support for node v0.12

### ISSUE THREAD

**Issue by eventualbuddha** [stefanpenner/broccoli-persistent-filter#135]
It's making [updating dependencies](https://github.com/stefanpenner/broccoli-persistent-filter/pull/134) impossible/hard. There's a pretty good chance it doesn't work out of the box on v0.12 anyway, and Appveyor doesn't run with it (only 4, 6, and 7 right now). I think we should be testing against 4, 6, 8, and 9. Possibly even just 6, 8, and 9.

**Comment by rwjblue** [comment]
> It's making updating dependencies impossible/hard.

Agreed, we should bump and drop 0.12 support.

> I think we should be testing against 4, 6, 8, and 9. Possibly even just 6, 8, and 9.

ember-cli supports all supported LTS versions, so we should go with 4, 6, 8, and 9.
