### ISSUE TITLE
broccoli-persistent-filter overwrites source files

### ISSUE THREAD

**Issue by joliss** [stefanpenner/broccoli-persistent-filter#143]
I discovered that under certain conditions, when the input node contains two conflicting files like `file.js` and `file.coffee`, broccoli-persistent-filter will overwrite files in the source directory. I'm not sure if the culprit is broccoli-persistent-filter or fs-tree-diff, so instead of writing a test case I just created a sample repo for now. To reproduce this issue, run:

```
git clone https://github.com/joliss/broccoli-persistent-filter-issue
cd broccoli-persistent-filter-issue
npm install
./node_modules/.bin/broccoli serve
```

Then in a new terminal, run

```
echo 's = "CoffeeScript source"' > src/file.coffee
sleep 1
git diff src/file.js
```

`src/file.js` has been overwritten with the CoffeeScript output.

**Comment by stefanpenner** [comment]
interesting...

**Comment by stefanpenner** [comment]
I see the issue:

1. build one
2.`src/file.js` is sylinked to `outputPath/src/file.js`
3. build two
4.`src/file.coffee`'s output is written to  `outputPath/src/file.js`, unfortunately `outputPath/src/file.js` is a symlink back to `src/file.js`

**Comment by stefanpenner** [comment]
The solution I believe is:

`_handleFile` should keep track of symlinks it created, and if they end up being overridden later they are first unlinked.

**Comment by stefanpenner** [comment]
thanks for reporting, sorry for lingering.
