### ISSUE TITLE
Allow tree to implement custom `cacheKey`

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/broccoli-persistent-filter#19]
I could be wrong (close if I am), but it seems like the individual tree can no longer specify its own `cacheKey`. Instead it always calls `hashForDep(ctx.baseDir())` ([here](https://github.com/stefanpenner/broccoli-persistent-filter/blob/18134ff395eaca3af9b4ff0caacc81c2a02d832f/lib/strategies/persistent.js#L21-L23)), but sometimes you need to make a custom `cacheKey` that is not related to `package.json` (for example: bower dependencies).

**Comment by stefanpenner** [comment]
Ya we should restore a hook on the plugin itself
