### ISSUE TITLE
persistent restore, always re-writes itself...

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/broccoli-persistent-filter#22]
This is slow.

**Comment by kellyselden** [comment]
That sounds like a challenge! :smile:

**Comment by stefanpenner** [comment]
@kellyselden would you like to take a stab? I can provide more info if you are interested

**Comment by kellyselden** [comment]
@stefanpenner Yea I can take a stab.

**Comment by stefanpenner** [comment]
Already fixed

**Comment by kellyselden** [comment]
darn
