### ISSUE TITLE
Add mechanism to clear persistent cache.

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/broccoli-persistent-filter#23]
It would be nice to have an environment variable that can be used to blow all the caches and force a fresh full build. Because async-disk-cache doesn't nest under a single base dir in the `os.tmpDir()` (I plan to submit a PR over there to do this), we cannot simply do `rm -rf /tmp/some/path/here` (even if we knew the path).

I would like to do something like:

```
CLEAR_PERSISTENT_CACHE=true ember build
```

And have that do something like the following just before the first boot ([before this](https://github.com/stefanpenner/broccoli-persistent-filter/blob/master/index.js#L72-L74)):

``` javascript
  this.processor.clear();
```

---

I'm happy to PR this, but wanted to throw it out there before I implemented to make sure there were no major objections...

**Comment by stefanpenner** [comment]
Yup. But make sure it saves state, so it only clears once per run

**Comment by rwjblue** [comment]
@stefanpenner - Confirm, it would have to set a flag so that it only does it one time (for each instance of `broccoli-persistent-filter`).

**Comment by stefanpenner** [comment]
Yup

**Comment by kyleshrader** [comment]
Was this functionality ever implemented?

**Comment by jeffsheets** [comment]
ran into an issue where i could use this too. What is the current easiest way to clear the persistent cache folders?

**Comment by jeffsheets** [comment]
For anyone else that stumbles upon this, I cleared it manually for me by going into node_modules/broccoli-persistent-filter/lib/strategies/persistent.js and adding a `this._cache.clear();` at the end of the init function after this._cache is initialized. And then removing it....
