### ISSUE TITLE
Add environment variable to override usage of `os.tmpDir()` in async-disk-cache.

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/broccoli-persistent-filter#24]
Moving over from https://github.com/stefanpenner/async-disk-cache/issues/2.

This would allow us to utilize a known path as the cache location, and then we can utilize Travis caching to take advantage of warm boots in CI also.

I would like https://github.com/stefanpenner/broccoli-persistent-filter/blob/master/lib/strategies/persistent.js#L15-L17 to become:

```javascript
    this._persistentCache = new AsyncDiskCache(ctx.constructor._persistentCacheKey, {
      compression: 'deflate',
      location: process.env['BROCCOLI_PERSISTENT_FILTER_CACHE_ROOT']
    });
```

The above would pass a `location` if that environment variable was set, and otherwise it would use the default (since https://github.com/stefanpenner/async-disk-cache/blob/master/index.js#L81 uses a falsey check on `options.location`).

Then we could use a path that is in the CI services (both Travis and Circle support these options) cached directory listing, and get much faster CI builds...

**Comment by stefanpenner** [comment]
:+1:
