### ISSUE TITLE
add concept for writing multiple files for one input

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/broccoli-persistent-filter#33]
basically to support writing `.map` files

It is possible today, but with hacks. It would be nicer if it was less hacky.

**Comment by davewasmer** [comment]
@stefanpenner any chance you could point me towards these hacks? Would be super useful for [broccoli-favicon](https://github.com/davewasmer/broccoli-favicon) (which in turn powers [ember-cli-favicon](https://github.com/davewasmer/ember-cli-favicon))

**Comment by stefanpenner** [comment]
We will revist this as another plugin likely. It will require a different API (most likely)

**Comment by buschtoens** [comment]
Has such a plugin, that is not specific to `.map` files, been written yet?

My use case: I transform certain custom functions in `.css` files to [`var()`](https://developer.mozilla.org/en-US/docs/Web/CSS/var) and want to save the meta information, e.g. which functions have been transformed with what selectors in a `.json` file, for a later processing stage.

For this, I could ideally return more than one output file for a given input file.

**Comment by buschtoens** [comment]
Seems like [`broccoli-multifilter`](https://github.com/broccolijs/broccoli-multifilter) is exactly what I'm after. AFAICT it makes the same cahing guarantees as `broccoli-persistent-filter`. 😊
