### ISSUE TITLE
Logging may no longer work

### ISSUE THREAD

**Issue by huiyuan** [stefanpenner/broccoli-persistent-filter#77]
`DEBUG=broccoli* ember s`a no longer yields  broccoli-persistent-filter logging.

**Comment by stefanpenner** [comment]
It appears this repo now relies on `DEBUG_LEVEL=debug` to print info. I believe we did this by mistake and `DEBUG_LEVEL=info` should actually provide atleast some-feedback.

We will fix

**Comment by stefanpenner** [comment]
cc @hjdivad

**Comment by stefanpenner** [comment]
latest should address this issue

**Comment by hjdivad** [comment]
@huiyuan it's just as @stefanpenner said.  The logging in persistent-filter 1.2.9 is all at log level `DEBUG` so `DEBUG=broccoli* DEBUG_LEVEL=debug ember s` will get you the detailed logging.  1.2.10 adds some more coarse grained logging at the default `DEBUG_LEVEL` of `info`.
