### ISSUE TITLE
Document limitations in Readme

### ISSUE THREAD

**Issue by davewasmer** [stefanpenner/broccoli-persistent-filter#86]
The readme mentions that the persistent cache does not work "on all systems":

> It is recommended that persistent re-builds is opt-in by the consumer as it does not currently work on all systems.

As tooling author, I'm trying to decide (a) whether I need to expose this option to my consumers, and (b) if so, when to recommend they disable the persistent cache.

A quick note about what systems have trouble would be helpful here. Doesn't need to be super detailed if that information doesn't exist - even just a "flakey on Windows" would work great.

**Comment by stefanpenner** [comment]
> It is recommended that persistent re-builds is opt-in by the consumer as it does not currently work on all systems.

ya, I'm not sure what this means either. It should work fine on all systems, but maybe not for all use-cases? For example, if a adequate cache-key cannot be created, then it should not be used.

**Comment by stefanpenner** [comment]
https://github.com/stefanpenner/broccoli-persistent-filter/pull/87 maybe?

**Comment by davewasmer** [comment]
Makes sense
