### ISSUE TITLE
Documentation for BROCCOLI_PERSISTENT_FILTER_CACHE_ROOT

### ISSUE THREAD

**Issue by MiLk** [stefanpenner/broccoli-persistent-filter#95]
Can we add `BROCCOLI_PERSISTENT_FILTER_CACHE_ROOT` to the README?

It would be easier to find a solution when https://github.com/stefanpenner/async-disk-cache/issues/35 happens.
Unfortunately, I didn't see anything in the ember documentation which could point to that issue and indicate how to not have that issue happen.

**Comment by rwjblue** [comment]
Would love a PR adding documentation for it!

**Comment by MiLk** [comment]
I never used ember, I'm just managing the servers for the developers at my company.
Could you explain me the purpose of this cache, so that I can write meaningful documentation (it's not even clear for me what broccoli-persistent-filter is doing)?

**Comment by rwjblue** [comment]
This package provides the ability to perform caching between one `ember build` / `ember serve` / `ember test --server` and another. This dramatically speeds up development by reducing the time it takes from one build to another.

**Comment by stefanpenner** [comment]
@rwjblue it may make more sense to document purging all async-disk cache's. As anything using them may be affected.


We need to warn, that if a persistent cache is purge while some other process is using it. Sad things may happen...
